### ISSUE TITLE
(UserBackgrounds) Fix 0 height

### ISSUE THREAD

**Issue by Pukimaa** [Strencher/BetterDiscordStuff#174]
Heya,
On the theme LilyPichu the Backgrounds (Nitro and USRBG) have a height of 0. To fix this, this CSS is needed:
```css
.UserBackgrounds-banner-container {
    display: flex;
    position: relative;
    height: 100%; /* This is new */
}
```

I am not very smart when it comes to Plugin Development so I won't open a PR and hope this CSS gets implemented.
I also tested it with other Themes (and no theme) and it does not break it!
