### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by reynoldyehezkiel** [Strencher/BetterDiscordStuff#188]
I have custom theme with transparent background. The plugin didn't match with my custom theme. So i need to know how to change it.
![image](https://user-images.githubusercontent.com/73789263/166426398-6d554e18-bbc6-451b-ba55-706ded308956.png)

Here's example from GuildProfile plugin (https://github.com/jaimeadf/BetterDiscordPlugins/tree/release/src/GuildProfile):
Before using custom theme
![image](https://user-images.githubusercontent.com/73789263/166427112-40b035b1-f077-48a9-ad46-b8716b06554f.png)
After using custom theme
![image](https://user-images.githubusercontent.com/73789263/166427440-4a69efde-7f75-43c7-a743-59d1d8d8fbdf.png)

**Comment by HypedDomi** [comment]
For the Header you could use
```css
.ChannelDms-channelmembers-header {
    background-color: transparent !important;
}
```
