### ISSUE TITLE
[PlatformIndicators] Conflicts with "RightAlignedNicks"

### ISSUE THREAD

**Issue by FichteFoll** [Strencher/BetterDiscordStuff#20]
I have a small custom theme called [RightAlignedNicks](https://github.com/FichteFoll/dotfiles/blob/master/BetterDiscord/.config/BetterDiscord/themes/RightAlignedNicks.theme.css) that provides a column-based view in compact layout.

When PlatformIndicators is active, it conflicts with that style because it overrides the `h2.header` styling with

```css
.header-23xsNx {
    display: flex !important;
    flex-direction: row !important;
}
```

where I need `display: inline-grid`. Are these overrides necessary?
