### ISSUE TITLE
[VoiceUserCOunter] Don't work ?

### ISSUE THREAD

**Issue by Soulivan71** [Strencher/BetterDiscordStuff#282]
Last version pl ; 
![image](https://user-images.githubusercontent.com/36502190/187052708-abff5fc6-3ef0-4751-b8ed-18393c4221a6.png)

**Comment by HypedDomi** [comment]
The counter is disabled on channels with a userlimit

**Comment by Soulivan71** [comment]
An improvement with option custom like 1/06 etc ?

**Comment by HypedDomi** [comment]
But Discord does this already

**Comment by Soulivan71** [comment]
Yeah but when we clic on a voice Channel Its hidden since the update with chat in VC

**Comment by HypedDomi** [comment]
Only when you hover over the channel

**Comment by HypedDomi** [comment]
@Soulivan71 Can i close the issue?

**Comment by Soulivan71** [comment]
Hmmm its + a suggestion that can be nice to turn on or off as preference

**Comment by HypedDomi** [comment]
You can do this with CSS:
```css
@media (hover: hover) {
    .iconVisibility-vptxma:hover .channelInfo-3jN1ay {
        display: block !important;
    }
}
```
Probably wont be added since its native in Discord
