### ISSUE TITLE
Option to make the pronoun text bold

### ISSUE THREAD

**Issue by jwax33** [Strencher/BetterDiscordStuff#40]
The current style has the pronouns a bit hard to see.  It would be great if there was an option (or a snippet of CSS code somewhere) we can use to make it bold to stand out better.

**Comment by Strencher** [comment]
```css
.PronounDB-pronouns-text {
    font-weight: bold;
}
```
here, have fun!
