### ISSUE TITLE
[UnreadCountBadges] Clicking on guild's count does not open it

### ISSUE THREAD

**Issue by rakosi2** [Strencher/BetterDiscordStuff#82]
If you click on the count, the guild icon does the little bounce confirming that I clicked on it but it does not actually open the guild. I have to make sure not to click on the count to actually open the guild.

**Comment by Strencher** [comment]
This little code snippet fixes your problem.
```css
.UnreadCountBadges-badge-unread {pointer-events: none;}
```
